/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.app.view;

import main.java.app.view.master.FormKaryawan;
import main.java.app.view.master.FormPelanggan;
import main.java.app.view.master.FormLayananCuci;
import main.java.app.view.master.FormKendaraan;
import main.java.app.view.master.FormJadwal;
import main.java.app.view.transaksi.FormTransaksi;
import main.java.app.view.transaksi.FormPembayaran;
import main.java.app.view.formreport.ReportKaryawan;
import main.java.app.view.formreport.ReportPelanggan;
import main.java.app.view.formreport.ReportTransaksi;
import main.java.app.view.formreport.ReportBulanan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import main.java.app.database.Koneksi;
import java.text.DecimalFormat;

/**
 *
 * @author aliframadhan
 */
public class Dashboard extends javax.swing.JFrame {
    private Connection koneksi = new Koneksi().connect();
    private String namaUser;
    private String jabatanUser;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
    
    public Dashboard(String namaUser, String jabatanUser) {
        initComponents();
        this.namaUser = namaUser;
        this.jabatanUser = jabatanUser;
        
        selamatDatang.setText("Selamat datang, " + namaUser + "!");
        
        if (!"admin".equalsIgnoreCase(jabatanUser)) {
            menuKaryawan.setEnabled(false);
        }
        loadDashboardData();
    }

    private void loadDashboardData() {
        try {
            Statement stat = koneksi.createStatement();

            // Ambil bulan sekarang di MySQL
            String sql = "SELECT " +
                         "COUNT(DISTINCT t.id_transaksi) AS jumlah, " +
                         "SUM(i.harga) AS total " +
                         "FROM transaksi t " +
                         "JOIN isi i ON t.id_transaksi = i.id_transaksi " +
                         "WHERE DATE_FORMAT(t.tgl_nota, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')";

            ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                int jumlah = rs.getInt("jumlah");
                double total = rs.getDouble("total");

                DecimalFormat df = new DecimalFormat("#,###.##");

                jumlahTransaksi.setText(String.valueOf(jumlah));
                totalPendapatan.setText("Rp" + df.format(total));
            }
        } catch (Exception e) {
            System.out.println("Error load dashboard: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selamatDatang = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jumlahTransaksi2 = new javax.swing.JLabel();
        totalPendapatan2 = new javax.swing.JLabel();
        jumlahTransaksi = new javax.swing.JLabel();
        totalPendapatan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mmaster = new javax.swing.JMenu();
        menuKaryawan = new javax.swing.JMenuItem();
        mJadwal = new javax.swing.JMenuItem();
        menuLayanan = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        mKendaraan = new javax.swing.JMenuItem();
        mtransaksi = new javax.swing.JMenu();
        menuTransaksi = new javax.swing.JMenuItem();
        mPembayaran = new javax.swing.JMenuItem();
        lkaryawan = new javax.swing.JMenu();
        lKaryawan = new javax.swing.JMenuItem();
        lPelanggan = new javax.swing.JMenuItem();
        lTransaksi = new javax.swing.JMenuItem();
        lBulanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selamatDatang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selamatDatang.setText("Halo");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard Cuci Steam");

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/assets/gambar/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jumlahTransaksi2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlahTransaksi2.setText("Jumlah Transaksi");

        totalPendapatan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalPendapatan2.setText("Total Pendapatan");

        jumlahTransaksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlahTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahTransaksi.setText(".");

        totalPendapatan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPendapatan.setText(".");

        mmaster.setText("Master");
        mmaster.setFocusable(false);
        mmaster.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuKaryawan.setText("Karyawan");
        menuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKaryawanActionPerformed(evt);
            }
        });
        mmaster.add(menuKaryawan);

        mJadwal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mJadwal.setText("Jadwal");
        mJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mJadwalActionPerformed(evt);
            }
        });
        mmaster.add(mJadwal);

        menuLayanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuLayanan.setText("Layanan");
        menuLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLayananActionPerformed(evt);
            }
        });
        mmaster.add(menuLayanan);

        menuPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        mmaster.add(menuPelanggan);

        mKendaraan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mKendaraan.setText("Kendaraan");
        mKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKendaraanActionPerformed(evt);
            }
        });
        mmaster.add(mKendaraan);

        jMenuBar1.add(mmaster);

        mtransaksi.setText("Transaksi");
        mtransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuTransaksi.setText("Transaksi");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        mtransaksi.add(menuTransaksi);

        mPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mPembayaran.setText("Pembayaran");
        mPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPembayaranActionPerformed(evt);
            }
        });
        mtransaksi.add(mPembayaran);

        jMenuBar1.add(mtransaksi);

        lkaryawan.setText("Laporan");
        lkaryawan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lKaryawan.setText("Laporan Karyawan");
        lKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lKaryawanActionPerformed(evt);
            }
        });
        lkaryawan.add(lKaryawan);

        lPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lPelanggan.setText("Laporan Pelanggan");
        lPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lPelangganActionPerformed(evt);
            }
        });
        lkaryawan.add(lPelanggan);

        lTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTransaksi.setText("Laporan Transaksi");
        lTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lTransaksiActionPerformed(evt);
            }
        });
        lkaryawan.add(lTransaksi);

        lBulanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lBulanan.setText("Laporan Bulanan");
        lBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lBulananActionPerformed(evt);
            }
        });
        lkaryawan.add(lBulanan);

        jMenuBar1.add(lkaryawan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selamatDatang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlahTransaksi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPendapatan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selamatDatang)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahTransaksi2)
                    .addComponent(totalPendapatan2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPendapatan)
                    .addComponent(jumlahTransaksi))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setBounds(0, 0, 479, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void menuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKaryawanActionPerformed
        // TODO add your handling code here:
        if (!"admin".equalsIgnoreCase(jabatanUser)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hanya Admin yang bisa mengakses menu Karyawan!");
            return;
        }
        
        FormKaryawan form = new FormKaryawan();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_menuKaryawanActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        // TODO add your handling code here:
        FormPelanggan form = new FormPelanggan();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLayananActionPerformed
        // TODO add your handling code here:
        FormLayananCuci form = new FormLayananCuci();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_menuLayananActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?",
                "konfirmasi Keluar",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if(konfirmasi == javax.swing.JOptionPane.YES_OPTION){
            java.awt.Window[] windows = java.awt.Window.getWindows();
            for(java.awt.Window window : windows){
                if(window instanceof javax.swing.JFrame){
                    window.dispose();
                }
            }
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void mKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKendaraanActionPerformed
        // TODO add your handling code here:
        FormKendaraan form = new FormKendaraan();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_mKendaraanActionPerformed

    private void mJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mJadwalActionPerformed
        // TODO add your handling code here:
        FormJadwal form = new FormJadwal();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_mJadwalActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        // TODO add your handling code here:
        FormTransaksi form = new FormTransaksi();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void lPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lPelangganActionPerformed
        // TODO add your handling code here:
        ReportPelanggan form = new ReportPelanggan();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_lPelangganActionPerformed

    private void lKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lKaryawanActionPerformed
        // TODO add your handling code here:
        ReportKaryawan form = new ReportKaryawan();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_lKaryawanActionPerformed

    private void lTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lTransaksiActionPerformed
        // TODO add your handling code here:
        ReportTransaksi form = new ReportTransaksi();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_lTransaksiActionPerformed

    private void lBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lBulananActionPerformed
    ReportBulanan form = new ReportBulanan();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();    // TODO add your handling code here:
    }//GEN-LAST:event_lBulananActionPerformed

    private void mPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPembayaranActionPerformed
        // TODO add your handling code here:
        FormPembayaran form = new FormPembayaran();
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        form.toFront();
        form.requestFocus();
    }//GEN-LAST:event_mPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jumlahTransaksi;
    private javax.swing.JLabel jumlahTransaksi2;
    private javax.swing.JMenuItem lBulanan;
    private javax.swing.JMenuItem lKaryawan;
    private javax.swing.JMenuItem lPelanggan;
    private javax.swing.JMenuItem lTransaksi;
    private javax.swing.JMenu lkaryawan;
    private javax.swing.JMenuItem mJadwal;
    private javax.swing.JMenuItem mKendaraan;
    private javax.swing.JMenuItem mPembayaran;
    private javax.swing.JMenuItem menuKaryawan;
    private javax.swing.JMenuItem menuLayanan;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuTransaksi;
    private javax.swing.JMenu mmaster;
    private javax.swing.JMenu mtransaksi;
    private javax.swing.JLabel selamatDatang;
    private javax.swing.JLabel totalPendapatan;
    private javax.swing.JLabel totalPendapatan2;
    // End of variables declaration//GEN-END:variables
}
