/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.app.view.transaksi;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author frdn1120
 */
public class FormNota extends javax.swing.JFrame {
JTextField tfId;
    JTextArea txtAreaNota;
    JButton btnCetak;
    /**
     * Creates new form FormNota
     */
    public FormNota(String id_transaksi) {
        initComponents();
        tfId.setText(id_transaksi); // isi otomatis dari RiwayatTransaksi
    }
public FormNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1207, 893));

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FORM NOTA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID Transaksi");

        cetak.setText("CETAK");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane1.setViewportView(txtNota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cetak)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cetak))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
    String cariitem = txtIdTransaksi.getText();

    try {
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cucisteam", "root", "");
        String sql = "SELECT * FROM transaksi_cuci WHERE id_transaksi LIKE '%" + cariitem + "%' " +
                     "OR tanggal_transaksi LIKE '%" + cariitem + "%' " +
                     "OR id_karyawan LIKE '%" + cariitem + "%' " +
                     "OR id_pelanggan LIKE '%" + cariitem + "%' " +
                     "OR id_layanan LIKE '%" + cariitem + "%' " +
                     "OR harga LIKE '%" + cariitem + "%' " +
                     "OR diskon LIKE '%" + cariitem + "%' " +
                     "OR metode_pembayaran LIKE '%" + cariitem + "%' " +
                     "ORDER BY id_transaksi ASC";

        Statement stat = koneksi.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        StringBuilder nota = new StringBuilder();

        while (hasil.next()) {
            nota.append("========== NOTA TRANSAKSI ==========\n");
            nota.append("ID Transaksi     : ").append(hasil.getString("id_transaksi")).append("\n");
            nota.append("Tanggal Transaksi: ").append(hasil.getString("tanggal_transaksi")).append("\n");
            nota.append("ID Karyawan      : ").append(hasil.getString("id_karyawan")).append("\n");
            nota.append("ID Pelanggan     : ").append(hasil.getString("id_pelanggan")).append("\n");
            nota.append("ID Layanan       : ").append(hasil.getString("id_layanan")).append("\n");
            nota.append("Harga            : Rp ").append(hasil.getString("harga")).append("\n");
            nota.append("Diskon           : ").append(hasil.getString("diskon")).append(" %\n");
            nota.append("Metode Pembayaran: ").append(hasil.getString("metode_pembayaran")).append("\n");

            // Hitung total setelah diskon (jika ada)
            double harga = hasil.getDouble("harga");
            double diskon = hasil.getDouble("diskon");
            double total = harga - (harga * diskon / 100);

            nota.append("Total Bayar      : Rp ").append(String.format("%.0f", total)).append("\n");
            nota.append("====================================\n\n");
        }

        if (nota.length() == 0) {
            txtNota.setText("Transaksi tidak ditemukan.");
        } else {
            txtNota.setText(nota.toString());
        }

        koneksi.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal ambil data transaksi: " + e.getMessage());
    }



    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
}
